# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Check for updates to CocoaPods dependencies
  - package-ecosystem: "swift"
    directory: "/" # Location of the Podfile
    schedule:
      interval: "daily" # Check for updates daily
    ignore:
      # Example: Ignore updates for specific dependencies
      - dependency-name: "Alamofire"
        versions: ["~> 5.2"]
  # Optional: Add any additional configurations or ecosystems if necessary
