# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # For CocoaPods dependencies
  - package-ecosystem: "cocoapods"
    directory: "/" # Path to your Podfile, usually the root directory
    schedule:
      interval: "weekly"
